"""notification fields: type, question, urgency, actions

Revision ID: 13f9570b0767
Revises: b8677871ede1
Create Date: 2026-08-25 01:21:22.419252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f9570b0767'
down_revision: Union[str, Sequence[str], None] = 'b8677871ede1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('suggested_actions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('urgency', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('admin_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_agent_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_notifications_urgency'), ['urgency'], unique=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=9), nullable=False))
        batch_op.drop_index(batch_op.f('ix_agent_notifications_urgency'))
        batch_op.drop_index(batch_op.f('ix_agent_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_agent_notifications_notification_type'))
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('admin_response')
        batch_op.drop_column('urgency')
        batch_op.drop_column('suggested_actions')
        batch_op.drop_column('question')
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
