"""baseline schema

Revision ID: 146457476197
Revises: 
Create Date: 2026-08-25 00:57:04.852825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146457476197'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_notifications',
    sa.Column('type', sa.Enum('AMBIGUITY', 'RESOURCE', 'DISCOVERY', 'ANOMALY', name='notificationtype'), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'ESCALATED', name='notificationstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_worker_accounts',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('proxy', sa.String(length=255), nullable=True),
    sa.Column('fingerprint_seed', sa.String(length=1024), nullable=False),
    sa.Column('stage', sa.Enum('WARM_UP', 'ACTIVE', 'RECOVERY', 'QUARANTINE', name='accountstage'), nullable=False),
    sa.Column('state', sa.Enum('HEALTHY', 'BLOCKED', name='accountstate'), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_worker_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_worker_accounts_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_worker_accounts_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_worker_accounts_state'), ['state'], unique=False)

    op.create_table('channel_configs',
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('authorized_users', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel')
    )
    op.create_table('chat_messages',
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('is_from_agent', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gold_eval_entries',
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('target_group', sa.String(length=255), nullable=True),
    sa.Column('dialect', sa.String(length=100), nullable=True),
    sa.Column('is_hate_speech', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexicon_entries',
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('raw_target_group', sa.String(length=100), nullable=True),
    sa.Column('scope', sa.Enum('GROUP_SPECIFIC', 'UNIVERSAL', name='termscope'), nullable=False),
    sa.Column('dialect', sa.JSON(), nullable=False),
    sa.Column('script', sa.JSON(), nullable=False),
    sa.Column('is_explicit', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('never_flag_when', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('pack_source', sa.String(length=255), nullable=True),
    sa.Column('pack_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lexicon_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lexicon_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_lexicon_entries_is_explicit'), ['is_explicit'], unique=False)
        batch_op.create_index(batch_op.f('ix_lexicon_entries_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_lexicon_entries_platform_id'), ['platform_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_lexicon_entries_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_lexicon_entries_term'), ['term'], unique=False)

    op.create_table('queue_items',
    sa.Column('stage', sa.Enum('DISCOVERY', 'PROCESSING', 'CLASSIFICATION', 'REVIEW', name='queuestage'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('tracked_account_id', sa.String(length=36), nullable=True),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('is_inflight', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.String(length=50), nullable=True),
    sa.Column('locked_by_worker', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_items_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_items_stage'), ['stage'], unique=False)

    op.create_table('severity_levels',
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auto_escalate', sa.Boolean(), nullable=False),
    sa.Column('pack_source', sa.String(length=255), nullable=True),
    sa.Column('pack_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    with op.batch_alter_table('severity_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_severity_levels_ordinal'), ['ordinal'], unique=True)

    op.create_table('target_groups',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name_en', sa.String(length=255), nullable=False),
    sa.Column('display_name_ar', sa.String(length=255), nullable=True),
    sa.Column('display_name_ku', sa.String(length=255), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('self_reference_terms', sa.JSON(), nullable=False),
    sa.Column('adjacent_groups', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('pack_source', sa.String(length=255), nullable=True),
    sa.Column('pack_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('target_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_target_groups_slug'), ['slug'], unique=True)

    op.create_table('trope_entries',
    sa.Column('trope_id', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Enum('GROUP_SPECIFIC', 'UNIVERSAL', name='termscope'), nullable=False),
    sa.Column('surface_forms', sa.JSON(), nullable=False),
    sa.Column('activation', sa.JSON(), nullable=False),
    sa.Column('implicature', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('positive_examples', sa.JSON(), nullable=False),
    sa.Column('negative_examples', sa.JSON(), nullable=False),
    sa.Column('counter_speech_examples', sa.JSON(), nullable=False),
    sa.Column('confirmed_in_cases', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('pack_source', sa.String(length=255), nullable=True),
    sa.Column('pack_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trope_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trope_entries_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_trope_entries_trope_id'), ['trope_id'], unique=True)

    op.create_table('cases',
    sa.Column('target_group_id', sa.String(length=36), nullable=False),
    sa.Column('narrative_pattern', sa.Text(), nullable=True),
    sa.Column('dialect_scope', sa.String(length=100), nullable=True),
    sa.Column('seed_posts', sa.JSON(), nullable=False),
    sa.Column('watch_keywords', sa.JSON(), nullable=False),
    sa.Column('target_pages', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'COOLING', 'DORMANT', 'REACTIVATED', name='casestate'), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('cooling_started_at', sa.String(length=50), nullable=True),
    sa.Column('dormant_started_at', sa.String(length=50), nullable=True),
    sa.Column('last_activity_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_group_id'], ['target_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_target_group_id'), ['target_group_id'], unique=False)

    op.create_table('lexicon_target_groups',
    sa.Column('lexicon_entry_id', sa.String(length=36), nullable=False),
    sa.Column('target_group_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['lexicon_entry_id'], ['lexicon_entries.id'], ),
    sa.ForeignKeyConstraint(['target_group_id'], ['target_groups.id'], ),
    sa.PrimaryKeyConstraint('lexicon_entry_id', 'target_group_id')
    )
    op.create_table('trope_target_groups',
    sa.Column('trope_entry_id', sa.String(length=36), nullable=False),
    sa.Column('target_group_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['target_group_id'], ['target_groups.id'], ),
    sa.ForeignKeyConstraint(['trope_entry_id'], ['trope_entries.id'], ),
    sa.PrimaryKeyConstraint('trope_entry_id', 'target_group_id')
    )
    op.create_table('llm_calls',
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_succeeded'), ['succeeded'], unique=False)

    op.create_table('tracked_accounts',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=1024), nullable=True),
    sa.Column('page_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('WARMUP', 'ACTIVE', 'BANNED', 'SUSPENDED', name='accountstatus'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'AUTONOMOUS', name='accountsource'), nullable=False),
    sa.Column('linked_case_id', sa.String(length=36), nullable=True),
    sa.Column('predecessor_account_id', sa.String(length=36), nullable=True),
    sa.Column('ban_reason', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.String(length=50), nullable=True),
    sa.Column('last_crawled_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['predecessor_account_id'], ['tracked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('tracked_account_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_media_urls', sa.JSON(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_profile_picture', sa.String(length=1024), nullable=True),
    sa.Column('queue_state', sa.Enum('DISCOVERY', 'PROCESSING', 'CLASSIFICATION', 'REVIEW', 'DONE', 'REJECTED', name='queuestate'), nullable=False),
    sa.Column('queue_priority', sa.Integer(), nullable=False),
    sa.Column('inflight_since', sa.String(length=50), nullable=True),
    sa.Column('target_group_id', sa.String(length=36), nullable=True),
    sa.Column('target_group_source', sa.String(length=20), nullable=True),
    sa.Column('dialect', sa.String(length=50), nullable=True),
    sa.Column('media_classification', sa.JSON(), nullable=True),
    sa.Column('classification_score', sa.Float(), nullable=True),
    sa.Column('hate_speech_flag', sa.Boolean(), nullable=True),
    sa.Column('multi_agent_trace', sa.JSON(), nullable=True),
    sa.Column('classification_model_versions', sa.JSON(), nullable=True),
    sa.Column('lexicon_version', sa.String(length=50), nullable=True),
    sa.Column('trope_version', sa.String(length=50), nullable=True),
    sa.Column('comments_total', sa.Integer(), nullable=False),
    sa.Column('comments_flagged', sa.Integer(), nullable=False),
    sa.Column('is_image_only', sa.Boolean(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_failed', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['target_group_id'], ['target_groups.id'], ),
    sa.ForeignKeyConstraint(['tracked_account_id'], ['tracked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_queue_state'), ['queue_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_target_group_id'), ['target_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_tracked_account_id'), ['tracked_account_id'], unique=False)

    op.create_table('comments',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('platform_comment_id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_profile_picture', sa.String(length=1024), nullable=True),
    sa.Column('classification_score', sa.Float(), nullable=True),
    sa.Column('hate_speech_flag', sa.Boolean(), nullable=True),
    sa.Column('multi_agent_trace', sa.JSON(), nullable=True),
    sa.Column('context_bundle_used', sa.Text(), nullable=True),
    sa.Column('missing_parent_flag', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)

    op.create_table('evidence_packages',
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('comment_id', sa.String(length=36), nullable=True),
    sa.Column('screenshot_path', sa.String(length=1024), nullable=False),
    sa.Column('html_snapshot_path', sa.String(length=1024), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=False),
    sa.Column('confirmed_at', sa.String(length=50), nullable=False),
    sa.Column('trope_fired', sa.String(length=255), nullable=True),
    sa.Column('multi_agent_trace_snapshot', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_packages_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_packages_post_id'), ['post_id'], unique=False)

    op.create_table('reviewer_decisions',
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('comment_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_id', sa.String(length=255), nullable=False),
    sa.Column('original_hate_speech_flag', sa.Boolean(), nullable=True),
    sa.Column('original_multi_agent_trace', sa.JSON(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('reviewer_rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviewer_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewer_decisions_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviewer_decisions_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewer_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewer_decisions_post_id'))
        batch_op.drop_index(batch_op.f('ix_reviewer_decisions_comment_id'))

    op.drop_table('reviewer_decisions')
    with op.batch_alter_table('evidence_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_packages_post_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_packages_comment_id'))

    op.drop_table('evidence_packages')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))

    op.drop_table('comments')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_tracked_account_id'))
        batch_op.drop_index(batch_op.f('ix_posts_target_group_id'))
        batch_op.drop_index(batch_op.f('ix_posts_queue_state'))
        batch_op.drop_index(batch_op.f('ix_posts_case_id'))

    op.drop_table('posts')
    op.drop_table('tracked_accounts')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_succeeded'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_purpose'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_post_id'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_model'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_case_id'))

    op.drop_table('llm_calls')
    op.drop_table('trope_target_groups')
    op.drop_table('lexicon_target_groups')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_target_group_id'))
        batch_op.drop_index(batch_op.f('ix_cases_severity'))

    op.drop_table('cases')
    with op.batch_alter_table('trope_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trope_entries_trope_id'))
        batch_op.drop_index(batch_op.f('ix_trope_entries_scope'))

    op.drop_table('trope_entries')
    with op.batch_alter_table('target_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_target_groups_slug'))

    op.drop_table('target_groups')
    with op.batch_alter_table('severity_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_severity_levels_ordinal'))

    op.drop_table('severity_levels')
    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_items_stage'))
        batch_op.drop_index(batch_op.f('ix_queue_items_priority'))

    op.drop_table('queue_items')
    with op.batch_alter_table('lexicon_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lexicon_entries_term'))
        batch_op.drop_index(batch_op.f('ix_lexicon_entries_scope'))
        batch_op.drop_index(batch_op.f('ix_lexicon_entries_platform_id'))
        batch_op.drop_index(batch_op.f('ix_lexicon_entries_language'))
        batch_op.drop_index(batch_op.f('ix_lexicon_entries_is_explicit'))
        batch_op.drop_index(batch_op.f('ix_lexicon_entries_category'))

    op.drop_table('lexicon_entries')
    op.drop_table('gold_eval_entries')
    op.drop_table('chat_messages')
    op.drop_table('channel_configs')
    with op.batch_alter_table('agent_worker_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_worker_accounts_state'))
        batch_op.drop_index(batch_op.f('ix_agent_worker_accounts_stage'))
        batch_op.drop_index(batch_op.f('ix_agent_worker_accounts_platform'))

    op.drop_table('agent_worker_accounts')
    op.drop_table('agent_notifications')
    # ### end Alembic commands ###
