"""trend signals and agent config

Revision ID: 6ef0c8279187
Revises: f973dfdc0847
Create Date: 2026-08-25 12:31:11.918297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef0c8279187'
down_revision: Union[str, Sequence[str], None] = 'f973dfdc0847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('default_value', sa.Float(), nullable=False),
    sa.Column('tuned_by', sa.Enum('HUMAN', 'AGENT', 'DEFAULT', name='tunedby'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_config_key'), ['key'], unique=True)

    op.create_table('trend_signals',
    sa.Column('target_group', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('hour_bucket', sa.String(length=20), nullable=False),
    sa.Column('items_scanned', sa.Integer(), nullable=False),
    sa.Column('items_flagged', sa.Integer(), nullable=False),
    sa.Column('hate_density', sa.Float(), nullable=False),
    sa.Column('observed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_group', 'platform', 'hour_bucket', name='uq_trend_bucket')
    )
    with op.batch_alter_table('trend_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_signals_hour_bucket'), ['hour_bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_signals_observed'), ['observed'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_signals_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_signals_target_group'), ['target_group'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trend_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_signals_target_group'))
        batch_op.drop_index(batch_op.f('ix_trend_signals_platform'))
        batch_op.drop_index(batch_op.f('ix_trend_signals_observed'))
        batch_op.drop_index(batch_op.f('ix_trend_signals_hour_bucket'))

    op.drop_table('trend_signals')
    with op.batch_alter_table('agent_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_config_key'))

    op.drop_table('agent_config')
    # ### end Alembic commands ###
