"""tracked account crawl interval and priority

Revision ID: 86db2c0d5e92
Revises: 13f9570b0767
Create Date: 2026-08-25 11:39:46.051765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86db2c0d5e92'
down_revision: Union[str, Sequence[str], None] = '13f9570b0767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_accounts', schema=None) as batch_op:
        # server_default is required, not cosmetic: SQLAlchemy's `default=` is applied
        # in Python, so the emitted DDL carries no default and SQLite refuses to add a
        # NOT NULL column to a table that already has rows.
        batch_op.add_column(
            sa.Column('crawl_interval_seconds', sa.Integer(), nullable=False, server_default='300')
        )
        batch_op.add_column(
            sa.Column('priority', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.create_index(batch_op.f('ix_tracked_accounts_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_accounts_priority'))
        batch_op.drop_column('priority')
        batch_op.drop_column('crawl_interval_seconds')

    # ### end Alembic commands ###
