"""trope category and visual form

Revision ID: 89044d38f9aa
Revises: 6ef0c8279187
Create Date: 2026-08-25 20:09:29.504383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89044d38f9aa'
down_revision: Union[str, Sequence[str], None] = '6ef0c8279187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trope_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        # server_default required: SQLAlchemy's `default=` applies in Python, so the
        # emitted DDL carries none and SQLite refuses a NOT NULL column on a
        # populated table.
        batch_op.add_column(
            sa.Column('is_visual', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('visual_form', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_trope_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_trope_entries_is_visual'), ['is_visual'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trope_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trope_entries_is_visual'))
        batch_op.drop_index(batch_op.f('ix_trope_entries_category'))
        batch_op.drop_column('visual_form')
        batch_op.drop_column('is_visual')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
