"""trope provenance

Revision ID: de545d5b2061
Revises: 89044d38f9aa
Create Date: 2026-08-25 20:18:28.604464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de545d5b2061'
down_revision: Union[str, Sequence[str], None] = '89044d38f9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trope_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('added_by', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trope_entries', schema=None) as batch_op:
        batch_op.drop_column('added_by')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
