"""follow state

Revision ID: f973dfdc0847
Revises: 86db2c0d5e92
Create Date: 2026-08-25 11:47:51.162017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f973dfdc0847'
down_revision: Union[str, Sequence[str], None] = '86db2c0d5e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_states',
    sa.Column('worker_account_id', sa.String(length=36), nullable=False),
    sa.Column('tracked_account_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REQUESTED', 'FOLLOWING', 'FAILED', 'UNFOLLOWED', name='followstatus'), nullable=False),
    sa.Column('followed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracked_account_id'], ['tracked_accounts.id'], ),
    sa.ForeignKeyConstraint(['worker_account_id'], ['agent_worker_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_account_id', 'tracked_account_id', name='uq_follow_pair')
    )
    with op.batch_alter_table('follow_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_states_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_states_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_states_tracked_account_id'), ['tracked_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_states_worker_account_id'), ['worker_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_states_worker_account_id'))
        batch_op.drop_index(batch_op.f('ix_follow_states_tracked_account_id'))
        batch_op.drop_index(batch_op.f('ix_follow_states_status'))
        batch_op.drop_index(batch_op.f('ix_follow_states_priority'))

    op.drop_table('follow_states')
    # ### end Alembic commands ###
